# yml ??
server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.cb8738oxfvy6.ap-northeast-2.rds.amazonaws.com:3306/ghproject-no01?allowMultiQueries=true
    username: lee4339
    password: 1q2w3e4r
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB

mybatis:
  mapper-locations:
    - /mappers/*.xml

#file:
#  path: C:/project/ghproject-no01-20230513/upload/
